(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const CFG=window.BIOOLYMP_CONFIG||{};
let client=null, duelBusy=false, lastLang='';
const L=()=>localStorage.getItem('bio7_lang')==='ru'?'ru':'kk';
const tx=(kk,ru)=>L()==='ru'?ru:kk;
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function core(){return window.BioOlympCore||null}
function state(){return core()?.state||null}
function getClient(){if(client)return client;if(!window.supabase?.createClient||!CFG.supabaseUrl||!CFG.supabaseAnonKey)return null;client=window.supabase.createClient(CFG.supabaseUrl,CFG.supabaseAnonKey);return client}
function localResults(){try{return JSON.parse(localStorage.getItem('bio7_results')||'[]')}catch{return []}}
function localMistakes(){try{return JSON.parse(localStorage.getItem('bio7_mistakes')||'{}')}catch{return {}}}
function ymd(d=new Date()){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
function mondayISO(){const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return ymd(d)}
function seeded(seed){let h=2166136261;for(const ch of String(seed)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return()=>{h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seededShuffle(a,seed){const r=seeded(seed),x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function questionNorm(raw,tid,source='base'){return {key:`${tid}:${raw.n??raw.id}`,topicId:Number(tid),n:raw.n??raw.id,q:raw.q,options:[...raw.options],answer:raw.answer,source,difficulty:raw.difficulty||1}}
function bestTopics(){const m={};localResults().forEach(r=>{if(r.topic_id!=null)m[r.topic_id]=Math.max(m[r.topic_id]||0,Number(r.score)||0)});return m}
function xpLocal(){return localResults().reduce((s,r)=>s+Math.round((Number(r.score)||0)/5)+(r.test_type==='olympiad'?10:0)+(r.test_type==='daily'?5:0),0)}
function coins(){return localResults().reduce((s,r)=>s+Math.max(1,Math.floor((Number(r.correct)||0)/3)),0)+unlocked().length*5}
function streakInfo(){const days=[...new Set(localResults().map(r=>ymd(new Date(r.created_at||Date.now()))))].sort().reverse();let s=0;let cursor=new Date();cursor.setHours(0,0,0,0);if(days[0]!==ymd(cursor)){cursor.setDate(cursor.getDate()-1);if(days[0]!==ymd(cursor))return {days:0,last:days[0]||null}}for(const d of days){if(d===ymd(cursor)){s++;cursor.setDate(cursor.getDate()-1)}else if(d<ymd(cursor))break}return {days:s,last:days[0]||null}}
function league(xp=xpLocal()){const list=[['Bronze','🥉',0,200],['Silver','🥈',200,500],['Gold','🥇',500,900],['Diamond','💎',900,1500],['BioChampion','🏆',1500,999999]];const cur=list.find(x=>xp>=x[2]&&xp<x[3])||list.at(-1);return {name:cur[0],ico:cur[1],min:cur[2],max:cur[3],pct:cur[3]>900000?100:Math.max(0,Math.min(100,Math.round((xp-cur[2])/(cur[3]-cur[2])*100)))}}
function unlocked(){try{return JSON.parse(localStorage.getItem('bio7_v4_achievements')||'[]')}catch{return []}}
function setUnlocked(x){localStorage.setItem('bio7_v4_achievements',JSON.stringify(x))}
const ACH=[
 {k:'first',ico:'🌱',kk:'Алғашқы қадам',ru:'Первый шаг',ok:()=>localResults().length>=1},
 {k:'q100',ico:'🧠',kk:'100 сұрақ',ru:'100 вопросов',ok:()=>localResults().reduce((s,r)=>s+(Number(r.total)||0),0)>=100},
 {k:'perfect',ico:'💯',kk:'Қатесіз тест',ru:'Тест без ошибок',ok:()=>localResults().some(r=>Number(r.score)>=100)},
 {k:'streak3',ico:'🔥',kk:'3 күн серия',ru:'Серия 3 дня',ok:()=>streakInfo().days>=3},
 {k:'streak7',ico:'🔥',kk:'7 күн серия',ru:'Серия 7 дней',ok:()=>streakInfo().days>=7},
 {k:'topics10',ico:'📚',kk:'10 тақырып 80%+',ru:'10 тем на 80%+',ok:()=>Object.values(bestTopics()).filter(x=>x>=80).length>=10},
 {k:'oly90',ico:'🏅',kk:'Olympiad 90%+',ru:'Olympiad 90%+',ok:()=>localResults().some(r=>r.test_type==='olympiad'&&Number(r.score)>=90)},
 {k:'clean',ico:'✨',kk:'Қателер тазаланды',ru:'Ошибки исправлены',ok:()=>{const a=Object.values(localMistakes());return a.length>0&&a.every(x=>x.resolved)}}
];
function checkAchievements(show=true){const old=unlocked(),set=new Set(old),fresh=[];for(const a of ACH){if(a.ok()&&!set.has(a.k)){set.add(a.k);fresh.push(a)}}const now=[...set];if(now.length!==old.length)setUnlocked(now);syncAchievementsRemote(now);if(show&&fresh[0])showAchievement(fresh[0]);return now}
function showAchievement(a){if($('.v4-achievement-pop'))return;const d=document.createElement('div');d.className='v4-achievement-pop';d.innerHTML=`<div><span>${a.ico}</span><small>${tx('ЖАҢА ЖЕТІСТІК','НОВОЕ ДОСТИЖЕНИЕ')}</small><b>${tx(a.kk,a.ru)}</b><button>OK</button></div>`;document.body.appendChild(d);d.querySelector('button').onclick=()=>d.remove();setTimeout(()=>d.remove(),6000)}
async function syncAchievementsRemote(keys){const c=getClient();if(!c)return;try{const {data:{session}}=await c.auth.getSession();if(!session||!keys.length)return;const rows=keys.map(k=>({user_id:session.user.id,achievement_key:k}));await c.from('student_achievements').upsert(rows,{onConflict:'user_id,achievement_key'})}catch(e){}
}
function ensureArena(){if($('#arena'))return;const main=$('main.page-wrap');if(!main)return;const sec=document.createElement('section');sec.className='view';sec.id='arena';sec.innerHTML='<div id="v4ArenaRoot"></div>';main.appendChild(sec);
 const dnav=$('#desktopNav');if(dnav&&!dnav.querySelector('[data-go="arena"]')){const b=document.createElement('button');b.dataset.go='arena';b.textContent=tx('Арена','Арена');const rating=dnav.querySelector('[data-go="rating"]');dnav.insertBefore(b,rating||null)}
 const drawer=$('#mobileDrawer');if(drawer&&!drawer.querySelector('[data-go="arena"]')){const b=document.createElement('button');b.dataset.go='arena';b.textContent=tx('🏆 Арена және жарыс','🏆 Арена и соревнования');const rating=drawer.querySelector('[data-go="rating"]');drawer.insertBefore(b,rating||null)}
}
function ensureHomeGame(){const host=$('#challengeHome');if(!host||$('#v4DailyHome'))return;const x=document.createElement('div');x.id='v4DailyHome';x.className='v4-home-game';host.after(x);renderHomeGame()}
function renderHomeGame(){const x=$('#v4DailyHome');if(!x)return;const st=streakInfo(),lg=league(),done=localResults().some(r=>r.title===`Daily Challenge • ${ymd()}`);x.innerHTML=`<div class="v4-daily-card"><div><span class="v4-kicker">DAILY CHALLENGE</span><h3>${done?tx('Бүгінгі challenge орындалды ✅','Сегодняшний challenge выполнен ✅'):tx('Бүгін 10 сұрақ. Қашып кетпе 😏','Сегодня 10 вопросов. Не убегай 😏')}</h3><p>${tx('Күн сайын орында — streak пен XP өседі.','Проходи каждый день — растут streak и XP.')}</p></div><button class="btn primary" id="v4DailyBtn" ${done?'disabled':''}>${done?tx('Дайын','Готово'):tx('Бастау','Начать')}</button></div><div class="v4-mini-stats"><div><span>🔥</span><b>${st.days}</b><small>${tx('күн серия','дней серия')}</small></div><div><span>${lg.ico}</span><b>${lg.name}</b><small>${xpLocal()} XP</small></div><div><span>🪙</span><b>${coins()}</b><small>BioCoin</small></div></div>`;$('#v4DailyBtn')?.addEventListener('click',startDaily)}
function startDaily(){const c=core();if(!c)return;const pool=[...c.allBaseQuestions(),...c.allProQuestions()];const qs=seededShuffle(pool,ymd()).slice(0,10);c.startQuiz({title:`Daily Challenge • ${ymd()}`,type:'daily',questions:qs,meta:{dailyDate:ymd()}})}
function weakData(){const best=bestTopics(),c=core();if(!c)return[];return (window.BIO_TOPICS||[]).map(t=>({id:Number(t.id),title:t.title,score:best[t.id]||0})).sort((a,b)=>a.score-b.score)}
function weakTraining(){const c=core();if(!c)return;const weak=weakData().slice(0,5).map(x=>x.id),pool=[];for(const id of weak){const t=c.topicById(id);if(t)pool.push(...t.questions.map(q=>questionNorm(q,id)))}if(!pool.length)return;c.startQuiz({title:tx('Әлсіз тақырыптар тренировкасы','Тренировка слабых тем'),type:'weak',questions:c.shuffle(pool).slice(0,15),meta:{weakTopics:weak}})}
function renderWeakMap(){const host=$('#accountRoot');if(!host)return;$('#v4ProgressLab')?.remove();const data=weakData(),active=Object.values(localMistakes()).filter(x=>!x.resolved),topWeak=data.filter(x=>x.score<80).slice(0,3);const wrap=document.createElement('div');wrap.id='v4ProgressLab';wrap.className='v4-progress-lab';wrap.innerHTML=`<div class="v4-section-title"><div><span>${tx('ЖЕКЕ АНАЛИТИКА','ЛИЧНАЯ АНАЛИТИКА')}</span><h3>${tx('Менің 63 тақырып картам','Моя карта 63 тем')}</h3></div><button class="btn soft" id="v4WeakTrain">${tx('Әлсіз тақырыптардан тест','Тест по слабым темам')}</button></div><div class="v4-smart-box"><b>${tx('Smart Mistakes','Smart Mistakes')}</b><p>${active.length?tx(`Қазір ${active.length} актив қате бар. Ең әлсіз: ${topWeak.map(x=>x.title.replace(/^§\\d+\\.\\s*/,'' )).join(', ')}`,`Сейчас ${active.length} активных ошибок. Самые слабые: ${topWeak.map(x=>x.title.replace(/^§\\d+\\.\\s*/,'' )).join(', ')}`):tx('Актив қате жоқ. Жақсы кетіп барасың 😌','Активных ошибок нет. Идёшь хорошо 😌')}</p></div><div class="v4-topic-map">${data.map(x=>`<button class="${x.score>=80?'strong':x.score>=50?'mid':'weak'}" data-v4-topic="${x.id}" title="${esc(x.title)} • ${x.score}%"><span>${x.id}</span><small>${x.score}%</small></button>`).join('')}</div><div class="v4-map-legend"><span><i class="weak"></i>${tx('әлсіз','слабо')} 0–49%</span><span><i class="mid"></i>${tx('орташа','средне')} 50–79%</span><span><i class="strong"></i>${tx('мықты','сильно')} 80%+</span></div>`;host.appendChild(wrap);$('#v4WeakTrain').onclick=weakTraining;$$('[data-v4-topic]',wrap).forEach(b=>b.onclick=()=>{const c=core(),t=c?.topicById(Number(b.dataset.v4Topic));if(!t)return;c.startQuiz({title:t.title,type:'topic',topicId:t.id,questions:t.questions.map(x=>questionNorm(x,t.id))})})}
function renderAchievementShelf(){const host=$('#accountRoot');if(!host)return;$('#v4AchievementShelf')?.remove();const got=new Set(checkAchievements(false));const lg=league(),st=streakInfo();const box=document.createElement('div');box.id='v4AchievementShelf';box.className='v4-achievement-shelf';box.innerHTML=`<div class="v4-section-title"><div><span>${tx('ГЕЙМИФИКАЦИЯ','ГЕЙМИФИКАЦИЯ')}</span><h3>${lg.ico} ${lg.name} League</h3></div><div class="v4-wallet">🪙 ${coins()} BioCoin</div></div><div class="v4-league-track"><i style="width:${lg.pct}%"></i></div><div class="v4-streak-line">🔥 <b>${st.days}</b> ${tx('күн қатарынан','дней подряд')} • ${xpLocal()} XP</div><div class="v4-ach-grid">${ACH.map(a=>`<div class="${got.has(a.k)?'on':'off'}"><span>${a.ico}</span><b>${tx(a.kk,a.ru)}</b>${got.has(a.k)?'<small>✓</small>':'<small>🔒</small>'}</div>`).join('')}</div>`;host.appendChild(box)}
async function fetchLeaderboard(){const c=getClient();if(!c)return[];try{const {data:{session}}=await c.auth.getSession();if(!session)return[];const {data}=await c.from('weekly_leaderboard').select('*').eq('week_start',mondayISO()).order('xp',{ascending:false}).limit(100);return data||[]}catch{return[]}}
function classBattle(rows){const m={};for(const r of rows){const k=r.class_name||tx('Сыныпсыз','Без класса');if(!m[k])m[k]={name:k,xp:0,students:0,best:0};m[k].xp+=Number(r.xp)||0;m[k].students++;m[k].best=Math.max(m[k].best,Number(r.best_score)||0)}return Object.values(m).sort((a,b)=>b.xp-a.xp)}
async function renderArena(){ensureArena();const root=$('#v4ArenaRoot');if(!root)return;root.innerHTML=`<div class="section-head"><div><span class="eyebrow">BIOOLYMP ARENA</span><h2>${tx('Жарыс алаңы','Арена соревнований')}</h2><p>${tx('Daily challenge, лигалар, сыныптар жарысы және 1 vs 1.','Daily challenge, лиги, битва классов и 1 vs 1.')}</p></div></div><div class="v4-arena-loading">${tx('Рейтинг жүктелуде...','Загружаю рейтинг...')}</div>`;const rows=await fetchLeaderboard(),st=streakInfo(),lg=league();let session=null;try{session=(await getClient()?.auth.getSession())?.data?.session}catch{}const classes=classBattle(rows),meIdx=session?rows.findIndex(x=>x.user_id===session.user.id):-1;const weekly=[['🏆',tx('Апта лидері','Лидер недели'),[...rows].sort((a,b)=>b.xp-a.xp)[0]],['📈',tx('Үздік прогресс','Лучший прогресс'),[...rows].sort((a,b)=>(b.progress_points||0)-(a.progress_points||0))[0]],['⚡',tx('Ең белсенді','Самый активный'),[...rows].sort((a,b)=>b.attempts-a.attempts)[0]]];root.innerHTML=`<div class="section-head"><div><span class="eyebrow">BIOOLYMP ARENA</span><h2>${tx('Жарыс алаңы','Арена соревнований')}</h2><p>${tx('Өзіңнің орныңды көр, қарсыластармен жарыс, лигаға көтеріл.','Смотри своё место, соревнуйся и поднимайся по лигам.')}</p></div></div><div class="v4-arena-hero"><div><small>${tx('МЕНІҢ ЛИГАМ','МОЯ ЛИГА')}</small><strong>${lg.ico} ${lg.name}</strong><span>${xpLocal()} XP • 🔥 ${st.days}</span></div><div><small>${tx('АПТАЛЫҚ ОРЫН','МЕСТО ЗА НЕДЕЛЮ')}</small><strong>${meIdx>=0?'#'+(meIdx+1):'—'}</strong><span>${meIdx>0?tx(`Алдыңғы оқушыға дейін +${Math.max(1,(rows[meIdx-1].xp||0)-(rows[meIdx].xp||0)+1)} XP`,`До следующего места +${Math.max(1,(rows[meIdx-1].xp||0)-(rows[meIdx].xp||0)+1)} XP`):tx('Лидер бол!','Стань лидером!')}</span></div></div><div class="v4-week-awards">${weekly.map(x=>`<div><span>${x[0]}</span><small>${x[1]}</small><b>${esc(x[2]?.display_name||'—')}</b></div>`).join('')}</div><div class="v4-arena-grid"><section><div class="v4-section-title"><div><span>CLASS BATTLE</span><h3>${tx('Сыныптар жарысы','Битва классов')}</h3></div></div><div class="v4-class-list">${classes.slice(0,10).map((x,i)=>`<div class="${i===0?'winner':''}"><span>#${i+1}</span><b>${esc(x.name)}</b><strong>${x.xp} XP</strong><small>${x.students} ${tx('оқушы','уч.')}</small></div>`).join('')||`<p>${tx('Әзірге мәлімет жоқ','Пока нет данных')}</p>`}</div></section><section><div class="v4-section-title"><div><span>1 VS 1</span><h3>${tx('Оқушыны шақыр','Брось вызов')}</h3></div></div><div id="v4Duels"></div></section></div><div class="v4-section-title" style="margin-top:18px"><div><span>TOP 20</span><h3>${tx('Жеке рейтинг','Личный рейтинг')}</h3></div></div><div class="v4-top-list">${rows.slice(0,20).map((r,i)=>`<div class="${session&&r.user_id===session.user.id?'me':''}"><span>#${i+1}</span><b>${esc(r.display_name)}</b><small>${esc(r.class_name||'')}</small><strong>${r.xp} XP</strong></div>`).join('')}</div>`;renderDuels(rows,session)}
async function renderDuels(rows,session){const root=$('#v4Duels');if(!root)return;if(!session){root.innerHTML=`<div class="v4-empty">${tx('1 vs 1 үшін кабинетке кір.','Войди в кабинет для 1 vs 1.')}</div>`;return}const c=getClient();if(!c)return;let duels=[];try{const {data,error}=await c.from('duels').select('*').or(`challenger_id.eq.${session.user.id},opponent_id.eq.${session.user.id}`).order('created_at',{ascending:false}).limit(20);if(error)throw error;duels=data||[]}catch(e){root.innerHTML=`<div class="v4-empty">${tx('1 vs 1 базасын қосу үшін V4 SQL-ді бір рет Run жаса.','Чтобы включить 1 vs 1, один раз запусти V4 SQL.')}</div>`;return}const active=duels.find(d=>d.status!=='completed'&&(d.challenger_id===session.user.id||d.opponent_id===session.user.id));const opp=rows.filter(x=>x.user_id!==session.user.id).slice(0,8);root.innerHTML=`${active?duelCard(active,session):`<select id="v4Opponent"><option value="">${tx('Қарсылас таңда...','Выбери соперника...')}</option>${opp.map(x=>`<option value="${x.user_id}">${esc(x.display_name)} • ${x.xp} XP</option>`).join('')}</select><button class="btn green" id="v4SendDuel">${tx('Вызов жіберу','Бросить вызов')}</button>`}<div class="v4-duel-history">${duels.filter(d=>d.status==='completed').slice(0,4).map(d=>`<small>⚔️ ${Number(d.challenger_score||0)}% : ${Number(d.opponent_score||0)}%</small>`).join('')}</div>`;$('#v4SendDuel')?.addEventListener('click',()=>createDuel($('#v4Opponent').value,session));$$('[data-v4-accept]').forEach(b=>b.onclick=()=>acceptDuel(b.dataset.v4Accept));$$('[data-v4-start]').forEach(b=>b.onclick=()=>startDuel(active,session))}
function duelCard(d,s){const incoming=d.opponent_id===s.user.id&&d.status==='pending';const mine=d.challenger_id===s.user.id?d.challenger_score:d.opponent_score;return `<div class="v4-duel-card"><span>⚔️ ${d.status.toUpperCase()}</span><b>${tx('1 vs 1 Challenge','1 vs 1 Challenge')}</b><small>${tx('10 бірдей сұрақ • нәтиже % бойынша','10 одинаковых вопросов • победа по %')}</small>${incoming?`<button class="btn green" data-v4-accept="${d.id}">${tx('Қабылдау','Принять')}</button>`:d.status==='active'&&mine==null?`<button class="btn green" data-v4-start="${d.id}">${tx('Дуэльді бастау','Начать дуэль')}</button>`:`<em>${mine!=null?tx(`Сенің нәтижең: ${mine}%`,`Твой результат: ${mine}%`):tx('Қарсыласты күтеміз','Ждём соперника')}</em>`}</div>`}
async function createDuel(uid,session){if(!uid)return;const c=getClient(),seed=`${Date.now()}-${session.user.id.slice(0,6)}-${uid.slice(0,6)}`;const {error}=await c.from('duels').insert({challenger_id:session.user.id,opponent_id:uid,question_seed:seed,question_count:10,status:'pending'});if(error)alert(error.message);else renderArena()}
async function acceptDuel(id){const c=getClient();const {error}=await c.rpc('accept_duel',{p_duel_id:id});if(error)alert(error.message);else renderArena()}
function startDuel(d,s){const c=core();if(!c||!d)return;const pool=[...c.allBaseQuestions(),...c.allProQuestions()];const qs=seededShuffle(pool,d.question_seed).slice(0,Number(d.question_count)||10);c.startQuiz({title:'1 vs 1 • BioOlymp Arena',type:'duel',questions:qs,timeLimit:12*60,meta:{duelId:d.id}})}
async function submitDuelScore(id,score){if(duelBusy)return;duelBusy=true;try{const c=getClient();if(!c)return;const {error}=await c.rpc('submit_duel_score',{p_duel_id:id,p_score:Number(score)});if(error)throw error;setTimeout(renderArena,400)}catch(e){console.warn('duel score',e)}finally{duelBusy=false}}
function languageWatch(){const cur=L();if(cur!==lastLang){lastLang=cur;ensureArena();ensureHomeGame();renderHomeGame();if($('#arena')?.classList.contains('active'))renderArena();if($('#account')?.classList.contains('active')){setTimeout(()=>{renderAchievementShelf();renderWeakMap()},50)}}}
function onNav(e){const b=e.target.closest('[data-go]');if(!b)return;const id=b.dataset.go;if(id==='arena')setTimeout(renderArena,60);if(id==='account')setTimeout(()=>{renderAchievementShelf();renderWeakMap()},180);if(id==='home')setTimeout(renderHomeGame,80)}
function init(){ensureArena();ensureHomeGame();checkAchievements(false);document.addEventListener('click',onNav);window.addEventListener('bioolymp:result',e=>{checkAchievements(true);renderHomeGame();const d=e.detail||{};if(d.meta?.duelId)submitDuelScore(d.meta.duelId,d.result?.score||0);if($('#account')?.classList.contains('active'))setTimeout(()=>{renderAchievementShelf();renderWeakMap()},100)});setInterval(languageWatch,900);setTimeout(()=>{if($('#account')?.classList.contains('active')){renderAchievementShelf();renderWeakMap()}},700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
window.BioOlympV4={renderArena,startDaily,weakTraining,checkAchievements};
})();
