-- BioOlymp 7: secure student accounts + teacher analytics
-- Run this ONCE in Supabase -> SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  full_name text not null,
  class_name text default '7 сынып',
  role text not null default 'student' check (role in ('student','teacher')),
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_type text not null,
  topic_id integer,
  title text,
  score integer not null check (score between 0 and 100),
  correct integer not null default 0,
  total integer not null default 0,
  duration_seconds integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists results_user_id_idx on public.results(user_id);
create index if not exists results_created_at_idx on public.results(created_at desc);
create index if not exists results_topic_id_idx on public.results(topic_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, full_name, class_name, role)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'username',''), split_part(new.email,'@',1)),
    coalesce(nullif(new.raw_user_meta_data->>'full_name',''), split_part(new.email,'@',1)),
    coalesce(nullif(new.raw_user_meta_data->>'class_name',''), '7 сынып'),
    'student'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid() and role = 'teacher'
  );
$$;

alter table public.profiles enable row level security;
alter table public.results enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.results from anon, authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert on table public.results to authenticated;
grant usage, select on sequence public.results_id_seq to authenticated;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_teacher());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self on public.profiles
for insert to authenticated
with check (id = auth.uid());

drop policy if exists results_select on public.results;
create policy results_select on public.results
for select to authenticated
using (user_id = auth.uid() or public.is_teacher());

drop policy if exists results_insert_self on public.results;
create policy results_insert_self on public.results
for insert to authenticated
with check (user_id = auth.uid());

-- AFTER you register your own account on the site, make it the teacher account.
-- Replace aidana with the login you registered:
-- update public.profiles set role='teacher' where username='aidana';
