-- BioOlymp 7 FINAL — extensions for assignments, mistakes, certificates, weekly ranking.
-- Run ONCE in Supabase SQL Editor. Safe to run after the previous BioOlymp schema.

create or replace function public.is_teacher()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='teacher');
$$;

-- IMPORTANT: profiles are not editable by students. Teacher role is changed only from SQL/admin.
revoke insert, update on table public.profiles from authenticated;
grant select on table public.profiles to authenticated;

drop policy if exists profiles_insert_self on public.profiles;
drop policy if exists profiles_update_self on public.profiles;
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (id=auth.uid() or public.is_teacher());

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  kind text not null default 'assignment' check (kind in ('assignment','olympiad','challenge')),
  topic_ids integer[] not null default '{}',
  question_count integer not null default 15 check(question_count between 1 and 100),
  time_limit_minutes integer not null default 0,
  due_at timestamptz,
  target_class text,
  target_user_id uuid references public.profiles(id) on delete cascade,
  max_attempts integer not null default 3,
  created_by uuid not null references public.profiles(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.results add column if not exists assignment_id uuid references public.assignments(id) on delete set null;

create table if not exists public.mistakes (
  user_id uuid not null references public.profiles(id) on delete cascade,
  question_key text not null,
  topic_id integer not null,
  wrong_count integer not null default 0,
  correct_streak integer not null default 0,
  resolved boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(user_id,question_key)
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  section_id text not null,
  section_title text not null,
  score integer not null,
  code text not null unique,
  issued_at timestamptz not null default now(),
  unique(user_id,section_id)
);

create table if not exists public.weekly_leaderboard (
  user_id uuid not null references public.profiles(id) on delete cascade,
  week_start date not null,
  display_name text not null,
  class_name text,
  attempts integer not null default 0,
  best_score integer not null default 0,
  total_score integer not null default 0,
  xp integer not null default 0,
  progress_points integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(user_id,week_start)
);

alter table public.weekly_leaderboard add column if not exists progress_points integer not null default 0;

create or replace function public.update_weekly_leaderboard()
returns trigger language plpgsql security definer set search_path=public as $$
declare p public.profiles%rowtype; w date; bonus integer;
begin
  select * into p from public.profiles where id=new.user_id;
  w := date_trunc('week',new.created_at)::date;
  bonus := case when new.test_type='olympiad' then 10 else 0 end;
  insert into public.weekly_leaderboard(user_id,week_start,display_name,class_name,attempts,best_score,total_score,xp,progress_points,updated_at)
  values(new.user_id,w,coalesce(p.full_name,p.username),p.class_name,1,new.score,new.score,round(new.score/5.0)::int+bonus,0,now())
  on conflict(user_id,week_start) do update set
    display_name=excluded.display_name,
    class_name=excluded.class_name,
    attempts=public.weekly_leaderboard.attempts+1,
    best_score=greatest(public.weekly_leaderboard.best_score,excluded.best_score),
    total_score=public.weekly_leaderboard.total_score+excluded.total_score,
    xp=public.weekly_leaderboard.xp+excluded.xp,
    progress_points=public.weekly_leaderboard.progress_points+greatest(excluded.best_score-public.weekly_leaderboard.best_score,0),
    updated_at=now();
  return new;
end;$$;

drop trigger if exists results_weekly_leaderboard on public.results;
create trigger results_weekly_leaderboard after insert on public.results for each row execute procedure public.update_weekly_leaderboard();

alter table public.assignments enable row level security;
alter table public.mistakes enable row level security;
alter table public.certificates enable row level security;
alter table public.weekly_leaderboard enable row level security;

revoke all on public.assignments,public.mistakes,public.certificates,public.weekly_leaderboard from anon,authenticated;
grant select on public.assignments,public.weekly_leaderboard to authenticated;
grant select,insert,update on public.mistakes,public.certificates to authenticated;
grant insert,update,delete on public.assignments to authenticated;
grant usage,select on sequence public.certificates_id_seq to authenticated;

-- assignments: teacher manages, students see own/class/global
create policy assignments_select on public.assignments for select to authenticated using (
  public.is_teacher()
  or target_user_id=auth.uid()
  or (target_user_id is null and (target_class is null or target_class=(select class_name from public.profiles where id=auth.uid())))
);
create policy assignments_teacher_insert on public.assignments for insert to authenticated with check(public.is_teacher() and created_by=auth.uid());
create policy assignments_teacher_update on public.assignments for update to authenticated using(public.is_teacher()) with check(public.is_teacher());
create policy assignments_teacher_delete on public.assignments for delete to authenticated using(public.is_teacher());

create policy mistakes_select on public.mistakes for select to authenticated using(user_id=auth.uid() or public.is_teacher());
create policy mistakes_insert on public.mistakes for insert to authenticated with check(user_id=auth.uid());
create policy mistakes_update on public.mistakes for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create policy certificates_select on public.certificates for select to authenticated using(user_id=auth.uid() or public.is_teacher());
create policy certificates_insert on public.certificates for insert to authenticated with check(user_id=auth.uid());
create policy certificates_update on public.certificates for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

create policy weekly_read on public.weekly_leaderboard for select to authenticated using(true);

create index if not exists assignments_active_idx on public.assignments(active,created_at desc);
create index if not exists mistakes_user_idx on public.mistakes(user_id,resolved);
create index if not exists weekly_week_idx on public.weekly_leaderboard(week_start,xp desc);


-- Backfill current week's existing results so the rating is not empty after first install.
insert into public.weekly_leaderboard(user_id,week_start,display_name,class_name,attempts,best_score,total_score,xp,progress_points,updated_at)
select r.user_id,date_trunc('week',r.created_at)::date,coalesce(p.full_name,p.username),p.class_name,
       count(*)::int,max(r.score)::int,sum(r.score)::int,
       sum(round(r.score/5.0)::int + case when r.test_type='olympiad' then 10 else 0 end)::int,
       0,now()
from public.results r join public.profiles p on p.id=r.user_id
where r.created_at >= date_trunc('week',now())
group by r.user_id,date_trunc('week',r.created_at)::date,p.full_name,p.username,p.class_name
on conflict(user_id,week_start) do update set
 display_name=excluded.display_name,class_name=excluded.class_name,attempts=excluded.attempts,
 best_score=excluded.best_score,total_score=excluded.total_score,xp=excluded.xp,updated_at=now();
